# Cloudflare Workers 설정 파일
name = "teamk-api"
main = "workers/teamk-api.js"
compatibility_date = "2024-01-01"

# D1 데이터베이스 바인딩
[[d1_databases]]
binding = "TEAMK_DB"
database_name = "teamk-data"
database_id = "" # 여기에 실제 D1 Database ID 입력

# Workers 환경 설정
[env.production]
name = "teamk-api"

# CORS 설정을 위한 환경 변수
[vars]
ALLOWED_ORIGINS = "https://teamk-airbnb.pages.dev"